import type { Metadata } from "next";
import "./globals.css";
import { Suspense } from "react";


export const metadata: Metadata = {
  title: "Data-Skate",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className=""
      >
        <Suspense>
        {children}
     </Suspense>
      </body>
    </html>
  );
}
